# Generated by Django 5.2.4 on 2025-08-07 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_promocao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocao',
            old_name='name',
            new_name='produto',
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='category',
        ),
    ]
